DROP DATABASE eCommerce_website;

CREATE DATABASE eCommerce_website;

USE eCommerce_website;

CREATE TABLE users (
    `userId` INT NULL DEFAULT NULL AUTO_INCREMENT,
	`userName` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
    `userPassword` VARCHAR(255) NULL DEFAULT NULL,
    `fullName` VARCHAR(255) NULL DEFAULT NULL,
    `email` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
    `phone` BIGINT(10) NULL DEFAULT NULL,
    `cardType` VARCHAR(255) NULL DEFAULT NULL,
    `cardNumber` VARCHAR(255) NULL DEFAULT NULL,
    `cardSecurity` VARCHAR(255) NULL DEFAULT NULL,
    `cardExp` DATETIME NULL DEFAULT NULL,
    `cardName` VARCHAR(255) NULL DEFAULT NULL,
    `lastFour` INT NULL DEFAULT NULL,
    `street` VARCHAR(255) NULL DEFAULT NULL,
    `city` VARCHAR(255) NULL DEFAULT NULL,
    `userState` VARCHAR(255) NULL DEFAULT NULL,
    `zip` INT NULL DEFAULT NULL,
    PRIMARY KEY(`userId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE contacts (
   `contactId` INT NULL DEFAULT NULL AUTO_INCREMENT,
   `contactName` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
   `contactEmail` VARCHAR(255) UNIQUE NULL DEFAULT NULL,
   `contactPhone` BIGINT(10) NULL DEFAULT NULL,
   `contactComment` BLOB NULL DEFAULT NULL,
   PRIMARY KEY(`contactId`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

